---
- name: Install vsftpd
  apt:
    name: vsftpd
    state: latest
    force_apt_get: yes

- name: Copy config file
  template:
    src: vsftpd.conf.j2
    dest: /etc/vsftpd.conf
    mode: '0644'
    backup: yes
  notify: vsftpd_reload

- name: Copy userlist file
  template:
    src: vsftpd.userlist.j2
    dest: /etc/vsftpd.userlist
    mode: '0644'
    backup: yes
  notify: vsftpd_reload

- name: Copy vsftpd pam file
  template:
    src: vsftpd.pam.j2
    dest: /etc/pam.d/vsftpd
    mode: '0644'
    backup: yes
  notify: vsftpd_reload

- name: Create ftp users with disabled shell
  user:
    name: "{{ item }}"
    shell: /sbin/nologin
    password: "{{ item | password_hash('sha512') }}"
    update_password: on_create
  when: vsftpd_users | length > 0
  loop: "{{ vsftpd_users }}"

- name: Ensure chroot directory is not writable
  file:
    path: "/home/{{ item }}/ftp"
    state: directory
    owner: nobody
    group: nogroup
    mode: 0555
  when: vsftpd_users | length > 0
  loop: "{{ vsftpd_users }}"

- name: Create ftp upload directory for ftp users
  file:
    path: "/home/{{ item }}/ftp/upload"
    state: directory
    owner: "{{ item }}"
    group: "{{ item }}"
    mode: 0755
  when: vsftpd_users | length > 0
  loop: "{{ vsftpd_users }}"

# TODO: Expose TLS ports when supported by Ansible role
- name: Expose relevant ports
  ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
  loop:
    - "{{ vsftpd_data_port }}"
    - "{{ vsftpd_command_port }}"
    # - "{{ vsftpd_tls_port }}"
    - "{{ vsftpd_pasv_min_port }}:{{ vsftpd_pasv_max_port }}"
  notify: ufw_reload

- name: Ensure vsftpd started
  service:
    name: vsftpd
    state: started
